title: Adolfo Neto
description: Elixir and Erlang enthusiast. Associate Professor at UTFPR

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - research.md

include: [ "/.well-known" ]


theme: jekyll-theme-dinky

